
-- must connect as sysdba to execute the following script
-- this manual script is to minimize the configuration change on the Oracle database server

-- we suggest you use the default SYSTEM user during the installation
-- if you choose a user other than SYSTEM during installation, you need change SYSTEM in the script to that username 

--METADATA TYPE:GRANT OBJECT:DBMS_JMS_PLSQL PRIVILEGE:EXECUTE GRANTEE:SYSTEM
GRANT EXECUTE ON sys.DBMS_REPUTIL TO SYSTEM with grant option 
/
--METADATA TYPE:GRANT OBJECT:DBMS_JMS_PLSQL PRIVILEGE:EXECUTE GRANTEE:SYSTEM
GRANT SELECT ON sys.DBA_VIEWS TO SYSTEM with grant option
/
--METADATA TYPE:GRANT OBJECT:DBMS_JMS_PLSQL PRIVILEGE:EXECUTE GRANTEE:SYSTEM
GRANT EXECUTE ON sys.DBMS_LOB TO SYSTEM with grant option
/
--METADATA TYPE:GRANT OBJECT:DBMS_JMS_PLSQL PRIVILEGE:EXECUTE GRANTEE:SYSTEM
GRANT EXECUTE ON sys.DBMS_SQL TO SYSTEM with grant option
/
--METADATA TYPE:GRANT OBJECT:DBMS_JMS_PLSQL PRIVILEGE:EXECUTE GRANTEE:SYSTEM
GRANT EXECUTE ON sys.DBMS_JOB TO SYSTEM with grant option
/
--METADATA TYPE:GRANT OBJECT:DBMS_JMS_PLSQL PRIVILEGE:EXECUTE GRANTEE:SYSTEM
GRANT EXECUTE ON sys.DBMS_RANDOM TO SYSTEM with grant option
/
--METADATA TYPE:GRANT OBJECT:V_$TRANSACTION PRIVILEGE:EXECUTE GRANTEE:SYSTEM
GRANT SELECT ON sys.V_$TRANSACTION TO SYSTEM with grant option 
/
--METADATA TYPE:GRANT OBJECT:GV_$TRANSACTION PRIVILEGE:EXECUTE GRANTEE:SYSTEM
GRANT SELECT ON sys.gv_$TRANSACTION TO SYSTEM with grant option 
/
